name = "Minecraft Forever World"
author = "toshi2d"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba575120cca64567859d9f3482e805bf83b0fa945480a04d07f80df4b077aa47"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
