name = "Minecraft Forever World"
author = "toshi2d"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "333d2dc48fb5ece929104de8f7237715aada784d8deb92019bf9e3b833689278"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
